/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
version = "2.0.0" // build/libs/ 에 버전이 명시되어 생긴다.

dependencies {
    // This dependency is used by the application.
      // log
    implementation("ch.qos.logback:logback-core:1.5.6")
    implementation("ch.qos.logback:logback-classic:1.5.6")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "bbg.BaseBallGame"
}

tasks.withType<Jar> {
  doLast {
    copy {
      from(layout.buildDirectory.dir("libs"))
      into("bbg/bin")
      rename("${rootProject.name}-${version}", "${rootProject.name}")
    }

    copy {
      from(layout.buildDirectory.dir("libs"))
      into("bbg/bin")      
    }
  }
}

// build 후 lib/* 파일들을 projectDir/lib/ 폴더로 복사 한다.
tasks.register<Copy>("deploy") {
    doFirst {
      delete("bbg/lib")
    }

    val target = "${rootProject.name}-${version}"

    from(zipTree("build/distributions/$target.zip")) {
        include("$target/lib/*")  
        eachFile {
            relativePath = RelativePath(true, *relativePath.segments.drop(1).toTypedArray())  
        }
        includeEmptyDirs = false  
    }
    into("bbg/")

    doLast {
      delete("bbg/lib/$target.jar")
    }
}

